window.__LANG_zh = {
  'app.name': '虚拟货币情报站',
  'nav.market': '行情总览',
  'nav.news': '资讯情报',
  'nav.chain': '链上洞察',
  'nav.ai': 'AI 助手',
  'ask.placeholder': '问点什么：BTC 技术面 / ETH 最新资讯 / 市场情绪',
  'ask.submit': '提问',
  'badge.checking': '数据源检测中',
  'badge.ws': 'WebSocket 实时推送',
  'badge.polling': '实时行情（轮询）',
  'badge.demo': '演示数据模式',
  'badge.mixed': '部分数据不可用',
  'badge.offline': '数据源不可用',
  'interval.15m': '15分钟',
  'interval.1h': '1小时',
  'interval.4h': '4小时',
  'interval.1d': '1天',
  'overlay.ma': 'MA',
  'overlay.boll': 'BOLL',
  'overlay.vol': 'VOL',
  'chart.loading': 'K 线数据加载中...',
  'chart.live': 'Binance 实时数据',
  'chart.demo': '演示数据（接口不可用）',
  'chart.high': '高',
  'chart.low': '低',
  'chart.vol': '量',
  'chart.open': '开',
  'chart.close': '收',
  'chart.source': '数据源',
  'indicators.title': '技术指标',
  'signals.title': '信号引擎',
  'signals.rescan': '重扫',
  'signals.empty': '当前 {symbol} 暂无触发信号',
  'signals.high': '高优先级',
  'signals.medium': '中优先级',
  'signals.low': '普通',
  'metric.rsi': 'RSI(14)',
  'metric.macd': 'MACD',
  'metric.ema': 'EMA12/26',
  'metric.sma': 'SMA20',
  'metric.atr': 'ATR',
  'metric.boll': '布林带',
  'metric.madz': 'MAD-Z 异常',
  'metric.ewma': 'EWMA 异动',
  'hint.rsiNeutral': '中性',
  'hint.rsiOversold': '超卖',
  'hint.rsiOverbought': '超买',
  'hint.macdBull': '多头动能',
  'hint.macdBear': '空头动能',
  'hint.trendBull': '多头',
  'hint.trendBear': '空头',
  'hint.priceAbove': '价格在上方',
  'hint.priceBelow': '价格在下方',
  'hint.bollUpper': '突破上轨',
  'hint.bollLower': '跌破下轨',
  'hint.anomalyNormal': '正常',
  'hint.anomaly': '异常波动',
  'hint.ewmaThreshold': '波动阈值 ±{v}%',
  'depth.title': '订单簿深度',
  'depth.bid': '买盘',
  'depth.ask': '卖盘',
  'depth.loading': '深度数据加载中...',
  'overview.gauge': '恐慌贪婪指数',
  'overview.totalMc': '总市值',
  'overview.vol24': '24h 成交额',
  'overview.btcShare': 'BTC 占比',
  'overview.ethShare': 'ETH 占比',
  'overview.movers': '24h 涨跌幅',
  'overview.change24': '24h',
  'sent.title': 'AI 情绪雷达',
  'sent.scoreLabel': '情绪分',
  'sent.tonePos': '偏乐观',
  'sent.toneNeg': '偏谨慎',
  'sent.toneNeu': '中性',
  'sent.based': '基于 {n} 条资讯的本地情感分析',
  'sent.positive': '利好',
  'sent.neutral': '中性',
  'sent.negative': '利空',
  'sent.local': '本地词典',
  'sent.updated': '更新',
  'news.title': '资讯流',
  'news.all': '全部',
  'news.allCoins': '全部币种',
  'news.noMatch': '没有符合条件的资讯',
  'news.original': '原文',
  'time.justNow': '刚刚',
  'time.minAgo': '{n} 分钟前',
  'time.hourAgo': '{n} 小时前',
  'time.dayAgo': '{n} 天前',
  'brief.title': 'AI 今日简报',
  'brief.refresh': '刷新',
  'chain.net': 'BTC 网络健康',
  'chain.fees': '手续费与内存池',
  'chain.defi': 'DeFi 链上 TVL',
  'chain.whale': '巨鲸雷达',
  'chain.flows': '交易所资金流向',
  'chain.whaleLive': 'Whale Alert 实时',
  'chain.whaleDemo': '演示数据 · 可配置 API Key',
  'chain.flowNote': '演示数据 · 生产环境建议接入 CryptoQuant / Glassnode',
  'chain.block': '区块高度',
  'chain.tx': '24h 交易笔数',
  'chain.hashrate': '全网算力 EH/s',
  'chain.miner': '矿工 24h 收入',
  'chain.fastest': '最快确认（sat/vB）',
  'chain.half': '半小时确认',
  'chain.hour': '1 小时确认',
  'chain.mempool': '内存池未确认交易 {n} 笔 · 约 {v} MB',
  'chain.in': '流入交易所',
  'chain.out': '流出交易所',
  'chain.loading': '链上数据加载中...',
  'ai.title': '智能问答',
  'ai.insight': 'AI 市场解读',
  'ai.timeline': '信号时间线',
  'ai.none': '暂无信号记录',
  'ai.welcomeTitle': '欢迎使用智能问答',
  'ai.welcome': '可以直接问：{price}、{rsi}、{news}、{sentiment}、{chain}，或者问我“什么是 MACD”。',
  'ai.preparing': '正在拉取 {symbol} 的 1 小时 K 线并计算指标...',
  'ai.suggestions': ['BTC 技术面分析', 'ETH 的 RSI 是多少', 'SOL 最新资讯', '市场情绪怎么样', '链上数据怎么样', '什么是布林带', 'BTC 价格'],
  'settings.title': '数据源与 API 配置',
  'settings.desc': '配置的密钥保存在本机浏览器（localStorage），用于启用扩展数据源。不配置时使用免费公开接口和内置演示数据。',
  'settings.whale': 'Whale Alert API Key（启用真实巨鲸监控）',
  'settings.cryptopanic': 'CryptoPanic API Key（启用实时多源资讯）',
  'settings.cryptocompare': 'CryptoCompare API Key（提高资讯接口配额）',
  'settings.optional': '可选',
  'settings.save': '保存配置',
  'settings.saved': '配置已保存，正在重新加载扩展数据源',
  'footer.disclaimer': '行情与资讯来自公开接口，不构成投资建议',
  'footer.source': '数据源：{live} 正常 / {demo} 兜底 · 更新于 {time}',
  'toast.switched': '已切换至 {symbol}',
  'toast.rescan': '信号引擎重新扫描完成',
  'toast.refreshed': '简报已刷新',
  'toast.insightRefreshed': '解读已重新生成',
  'status.ok': '正常',
  'status.unavailable': '不可用',
  'status.connecting': '连接中',
  'status.demo': '已切换演示数据',
  'status.checkKey': '请检查密钥',
  'status.binance': 'Binance 行情',
  'status.klines': 'K 线',
  'status.depth': '深度',
  'status.news': '资讯',
  'status.cryptopanic': 'CryptoPanic 资讯',
  'status.fng': '情绪指数',
  'status.global': '全局数据',
  'status.blockchain': 'BTC 网络统计',
  'status.mempool': '手续费与内存池',
  'status.defillama': 'DefiLlama',
  'status.whale': 'Whale Alert',
  'status.ws': 'WebSocket',
  'sig.type.mean': '均值回归',
  'sig.type.momentum': '动量',
  'sig.type.trend': '趋势',
  'sig.type.breakout': '突破',
  'sig.type.anomaly': '异常检测',
  'sig.type.move': '涨跌幅',
  'sig.rsiOs.title': '{symbol} RSI 超卖 {v}',
  'sig.rsiOs.msg': 'RSI 低于 30，短线存在超卖修复机会，需结合趋势确认。',
  'sig.rsiOb.title': '{symbol} RSI 超买 {v}',
  'sig.rsiOb.msg': 'RSI 高于 70，短线追高风险上升，注意获利回吐。',
  'sig.macdBull.title': '{symbol} MACD 金叉',
  'sig.macdBull.msg': 'MACD 柱由负转正，动能转向多头。',
  'sig.macdBear.title': '{symbol} MACD 死叉',
  'sig.macdBear.msg': 'MACD 柱由正转负，动能转向空头。',
  'sig.emaBull.title': '{symbol} EMA 金叉',
  'sig.emaBull.msg': 'EMA12 上穿 EMA26，中期趋势转多。',
  'sig.emaBear.title': '{symbol} EMA 死叉',
  'sig.emaBear.msg': 'EMA12 下穿 EMA26，中期趋势转空。',
  'sig.bollUp.title': '{symbol} 突破布林上轨',
  'sig.bollUp.msg': '价格突破布林上轨，波动放大，关注动量延续或均值回归。',
  'sig.bollDown.title': '{symbol} 跌破布林下轨',
  'sig.bollDown.msg': '价格跌破布林下轨，波动加剧，注意风险控制。',
  'sig.anomalyZ.title': '{symbol} 异常波动（MAD-Z）',
  'sig.anomalyZ.msg': '修正 Z-Score {v}，单根 K 线收益显著偏离中位数。',
  'sig.anomalyEwma.title': '{symbol} EWMA 异动',
  'sig.anomalyEwma.msg': '指数加权收益偏离常态波动 {v}%，注意成交量配合。',
  'sig.move.title': '{symbol} 24h {pct}',
  'sig.move.msg': '单日波幅超过 5%，关注成交量与消息面。',
  'ai.techSec': '技术面',
  'ai.newsSec': '消息面',
  'ai.verdictSec': '综合判断',
  'ai.insightIntro': '{symbol}（{name}）当前报 {price}{change}。趋势状态 {trend}，RSI(14) 为 {rsi}，MACD 处于 {macd}，价格位于{bb}。',
  'ai.insightVol': 'ATR 相对价格为 {v}%，波动率{vol}。',
  'ai.volHigh': '偏高，注意仓位控制',
  'ai.volLow': '偏低，行情或临近收敛选择方向',
  'ai.volMid': '处于中性区间',
  'ai.newsSummary': '近 30 条资讯中涉及 {symbol} 的有 {n} 条：利好 {pos}、利空 {neg}、中性 {neu}。{tone}',
  'ai.newsTonePos': '情绪偏暖，消息面与技术面共振概率较高。',
  'ai.newsToneNeg': '情绪偏谨慎，留意利空发酵风险。',
  'ai.newsToneNeu': '多空信号交织，趋势确认更依赖资金面。',
  'ai.noNews': '当前资讯流中暂未检测到 {symbol} 的强相关新闻，行情主要由盘面资金与宏观情绪驱动。',
  'ai.headline': '最新相关资讯：{title}',
  'ai.fngHigh': '市场偏贪婪，追高需谨慎。',
  'ai.fngLow': '市场偏恐慌，关注超跌机会。',
  'ai.fngMid': '情绪中性，按技术信号操作。',
  'ai.fngSuffix': ' 市场恐慌贪婪指数为 {v}（{label}），整体风险偏好{level}。',
  'ai.verdictBull': '趋势与情绪共振偏多，可关注回踩均线的顺势机会，但要防止高位放量回落。',
  'ai.verdictBear': '弱势特征明显，反弹力度有限，等待企稳信号或消息面转暖。',
  'ai.verdictOversold': '短线进入超卖区，均值回归策略可观察，但趋势未转多前不宜重仓左侧。',
  'ai.verdictOverbought': '短线超买，动量仍强但追高风险大，适合持仓者分批兑现而非追涨。',
  'ai.verdictNeutral': '多空处于拉锯阶段，建议等待 EMA 交叉或布林带突破给出更明确方向。',
  'ai.priceTitle': '{symbol} 实时行情',
  'ai.priceHtml': '{symbol}（{name}）当前价格 {price} USDT，24h {pct}。24h 最高 {high}，最低 {low}。成交量约 {vol} {symbol}，成交额 {quote} USDT。数据源：{source}',
  'ai.rsiTitle': '{symbol} RSI(14)',
  'ai.rsiHtml': '{symbol} 当前 RSI(14) 为 {v}，处于{state}。',
  'ai.rsiExplain': '超卖不代表立刻反弹，通常需等待动量背离或企稳信号。',
  'ai.rsiExplainOb': '超买阶段趋势可能延续，追高需控制风险。',
  'ai.rsiExplainNeu': '中性区意味着多空力量均衡，参考 MACD 与均线判断方向。',
  'ai.rsiStateOs': '超卖区',
  'ai.rsiStateOb': '超买区',
  'ai.rsiStateNeu': '中性区',
  'ai.trendTitle': '{symbol} 趋势结构',
  'ai.trendHtml': '{symbol} 当前趋势状态：{trend}。EMA12 {e12} / EMA26 {e26}，SMA20 {sma}。{advice}',
  'ai.trendAdviceBull': '均线系统多头排列，回踩支撑位关注持续性。',
  'ai.trendAdviceBear': '均线系统空头排列，反弹承压概率更高。',
  'ai.signalTitle': '{symbol} 最新信号',
  'ai.signalNone': '当前没有针对 {symbol} 的活跃信号。',
  'ai.newsTitle': '{symbol} 相关资讯',
  'ai.newsNone': '当前资讯流中没有检测到与 {symbol} 强相关的新闻。',
  'ai.newsList': '近 30 条资讯中相关 {n} 条：利好 {pos} / 利空 {neg} / 中性 {neu}。',
  'ai.sentimentTitle': '市场情绪总览',
  'ai.sentimentHtml': '恐慌贪婪指数：{v} / 100（{label}）。资讯流 {n} 条：利好 {pos} / 利空 {neg} / 中性 {neu}。{advice}',
  'ai.chainTitle': '链上数据',
  'ai.chainHtml': 'BTC 网络：{block}。链上手续费（sat/vB）：最快 {f}，半小时 {h}，1 小时 {hour}。DeFi 前 3 链 TVL：{defi}。',
  'ai.chainLoading': '数据加载中',
  'ai.marketTitle': '市场概览',
  'ai.marketHtml': '加密货币总市值约 {mc} USD，24h 成交额 {vol} USD，BTC 占比 {dom}。{fng}',
  'ai.helpTitle': '试试这样问',
  'ai.helpHtml': '{a}、{b}、{c}、{d}、{e}，或者问“什么是 MACD”。',
  'ai.def.rsi.t': 'RSI（相对强弱指标）',
  'ai.def.rsi.h': 'RSI 衡量一段时间内涨跌力量的相对强弱，范围 0-100。通常高于 70 视为超买，低于 30 视为超卖，结合趋势使用效果更好。',
  'ai.def.macd.t': 'MACD（指数平滑异同平均线）',
  'ai.def.macd.h': 'MACD 由快慢 EMA 之差（DIF）、信号线（DEA）和柱状图构成。DIF 上穿 DEA 为金叉，下穿为死叉，柱状图反映动能强弱。',
  'ai.def.boll.t': '布林带（Bollinger Bands）',
  'ai.def.boll.h': '布林带由中轨（SMA20）与上下轨（±2 倍标准差）构成。价格触轨通常代表波动放大，突破后可能是趋势启动，也可能是均值回归信号。',
  'ai.def.ma.t': '移动平均线（MA/EMA）',
  'ai.def.ma.h': '均线平滑价格波动，识别趋势方向。MA 是简单平均，EMA 对近期价格加权更大。均线金叉/死叉常用于趋势切换判断。',
  'ai.def.atr.t': 'ATR（平均真实波幅）',
  'ai.def.atr.h': 'ATR 衡量平均波动幅度，数值越高波动越大，常用于设置止损和评估仓位大小。',
  'ai.def.whale.t': '巨鲸（Whale）',
  'ai.def.whale.h': '巨鲸指持有大量加密资产的钱包或机构。巨鲸大额转账和买卖通常被视为市场情绪与流动性的重要信号。',
  'ai.def.zscore.t': '修正 Z-Score 异常检测',
  'ai.def.zscore.h': '修正 Z-Score 使用中位数与 MAD 计算，对异常值更稳健。本系统用它检测单根 K 线收益是否显著偏离常态。',
  'brief.marketLine': '恐慌贪婪指数 {fng}，总市值约 {mc} USD{mcchg}。BTC 市值占比 {dom}。',
  'brief.moversTitle': '24h 领涨领跌',
  'brief.newsTitle': '资讯情绪',
  'brief.newsLine': '当前资讯流 {n} 条，利好 {pos} / 利空 {neg} / 中性 {neu}，整体情绪{tone}。',
  'brief.headlineTitle': '头条',
  'brief.signalsTitle': '信号提示',
  'brief.signalsLine': '信号引擎当前检测到 {n} 条触发信号{high}。',
  'brief.disclaimer': '以上内容由本地规则引擎基于公开数据自动生成，不构成投资建议。',
  'common.close': '关闭',
  'ai.subtitle': '自然语言查询市场数据',
  'ai.chatPlaceholder': '输入问题，如：ETH 的 RSI 是多少？',
  'ai.reinterpret': '重新解读',
  'chain.table.chain': '公链',
  'chain.table.tvl': 'TVL (USD)',
  'chain.table.change': '24h',
  'chain.table.share': '占比',
  'sig.type.rsi': 'RSI',
  'sig.type.macd': 'MACD',
  'sig.type.ema': 'EMA',
  'sig.type.boll': 'BOLL',
  'status.ticker24': 'REST 24 小时行情',
  'status.symbols': '{n} 个币种',
  'status.symbols1h': '{n} 个币种 1h',
  'status.items': '{n} 条资讯',
  'status.txCount': '{n} 笔交易',
  'meta.desc': '实时行情、K线、技术指标、资讯情绪与链上数据监控'
};
