window.__LANG_en = {
  'app.name': 'Crypto Intelligence Hub',
  'nav.market': 'Market',
  'nav.news': 'News',
  'nav.chain': 'On-chain',
  'nav.ai': 'AI Assistant',
  'ask.placeholder': 'Ask: BTC technicals / latest ETH news / market sentiment',
  'ask.submit': 'Ask',
  'badge.checking': 'Checking data sources',
  'badge.ws': 'WebSocket live feed',
  'badge.polling': 'Live data (polling)',
  'badge.demo': 'Demo data mode',
  'badge.mixed': 'Some sources unavailable',
  'badge.offline': 'Data sources unavailable',
  'interval.15m': '15m',
  'interval.1h': '1h',
  'interval.4h': '4h',
  'interval.1d': '1d',
  'overlay.ma': 'MA',
  'overlay.boll': 'BOLL',
  'overlay.vol': 'VOL',
  'chart.loading': 'Loading candlestick data...',
  'chart.live': 'Binance live data',
  'chart.demo': 'Demo data (API unavailable)',
  'chart.high': 'H',
  'chart.low': 'L',
  'chart.vol': 'Vol',
  'chart.open': 'O',
  'chart.close': 'C',
  'chart.source': 'Source',
  'indicators.title': 'Indicators',
  'signals.title': 'Signal Engine',
  'signals.rescan': 'Rescan',
  'signals.empty': 'No active signals for {symbol}',
  'signals.high': 'High',
  'signals.medium': 'Medium',
  'signals.low': 'Normal',
  'metric.rsi': 'RSI(14)',
  'metric.macd': 'MACD',
  'metric.ema': 'EMA12/26',
  'metric.sma': 'SMA20',
  'metric.atr': 'ATR',
  'metric.boll': 'Bollinger',
  'metric.madz': 'MAD-Z',
  'metric.ewma': 'EWMA',
  'hint.rsiNeutral': 'Neutral',
  'hint.rsiOversold': 'Oversold',
  'hint.rsiOverbought': 'Overbought',
  'hint.macdBull': 'Bullish momentum',
  'hint.macdBear': 'Bearish momentum',
  'hint.trendBull': 'Bullish',
  'hint.trendBear': 'Bearish',
  'hint.priceAbove': 'Price above',
  'hint.priceBelow': 'Price below',
  'hint.bollUpper': 'Above upper band',
  'hint.bollLower': 'Below lower band',
  'hint.anomalyNormal': 'Normal',
  'hint.anomaly': 'Anomaly',
  'hint.ewmaThreshold': 'Threshold ±{v}%',
  'depth.title': 'Order Book Depth',
  'depth.bid': 'Bids',
  'depth.ask': 'Asks',
  'depth.loading': 'Loading depth data...',
  'overview.gauge': 'Fear & Greed Index',
  'overview.totalMc': 'Market Cap',
  'overview.vol24': '24h Volume',
  'overview.btcShare': 'BTC Dominance',
  'overview.ethShare': 'ETH Dominance',
  'overview.movers': '24h Movers',
  'overview.change24': '24h',
  'sent.title': 'AI Sentiment Radar',
  'sent.scoreLabel': 'Score',
  'sent.tonePos': 'Bullish',
  'sent.toneNeg': 'Cautious',
  'sent.toneNeu': 'Neutral',
  'sent.based': 'Local sentiment over {n} news items',
  'sent.positive': 'Positive',
  'sent.neutral': 'Neutral',
  'sent.negative': 'Negative',
  'sent.local': 'Local lexicon',
  'sent.updated': 'updated',
  'news.title': 'News Feed',
  'news.all': 'All',
  'news.allCoins': 'All coins',
  'news.noMatch': 'No news matches the current filters',
  'news.original': 'Original',
  'time.justNow': 'just now',
  'time.minAgo': '{n}m ago',
  'time.hourAgo': '{n}h ago',
  'time.dayAgo': '{n}d ago',
  'brief.title': 'AI Daily Brief',
  'brief.refresh': 'Refresh',
  'chain.net': 'BTC Network Health',
  'chain.fees': 'Fees & Mempool',
  'chain.defi': 'DeFi TVL by Chain',
  'chain.whale': 'Whale Radar',
  'chain.flows': 'Exchange Flows',
  'chain.whaleLive': 'Whale Alert live',
  'chain.whaleDemo': 'Demo data · API key configurable',
  'chain.flowNote': 'Demo data · connect CryptoQuant / Glassnode for production',
  'chain.block': 'Block height',
  'chain.tx': '24h transactions',
  'chain.hashrate': 'Hashrate EH/s',
  'chain.miner': '24h miner revenue',
  'chain.fastest': 'Fastest fee (sat/vB)',
  'chain.half': 'Half hour fee',
  'chain.hour': '1 hour fee',
  'chain.mempool': 'Mempool: {n} unconfirmed tx · ~{v} MB',
  'chain.in': 'Inflow to exchange',
  'chain.out': 'Outflow from exchange',
  'chain.loading': 'Loading on-chain data...',
  'ai.title': 'Smart Q&A',
  'ai.insight': 'AI Market Insight',
  'ai.timeline': 'Signal Timeline',
  'ai.none': 'No signals recorded',
  'ai.welcomeTitle': 'Welcome',
  'ai.welcome': 'Try asking: {price}, {rsi}, {news}, {sentiment}, {chain}, or ask "what is MACD?".',
  'ai.preparing': 'Fetching 1h candles for {symbol} and computing indicators...',
  'ai.suggestions': ['BTC technical analysis', 'What is ETH RSI?', 'Latest SOL news', 'How is market sentiment?', 'How is on-chain data?', 'What is Bollinger Bands?', 'BTC price'],
  'settings.title': 'Data Sources & API Keys',
  'settings.desc': 'Keys are stored only in this browser (localStorage) to enable premium sources. Without keys the app uses free public APIs and built-in demo data.',
  'settings.whale': 'Whale Alert API Key (live whale monitoring)',
  'settings.cryptopanic': 'CryptoPanic API Key (multi-source news)',
  'settings.cryptocompare': 'CryptoCompare API Key (higher news quota)',
  'settings.optional': 'optional',
  'settings.save': 'Save',
  'settings.saved': 'Settings saved, reloading extended data sources',
  'footer.disclaimer': 'Market data and news come from public APIs and are not investment advice',
  'footer.source': 'Sources: {live} live / {demo} fallback · updated {time}',
  'toast.switched': 'Switched to {symbol}',
  'toast.rescan': 'Signal engine rescanned',
  'toast.refreshed': 'Brief refreshed',
  'toast.insightRefreshed': 'Insight regenerated',
  'status.ok': 'OK',
  'status.unavailable': 'unavailable',
  'status.connecting': 'connecting',
  'status.demo': 'demo fallback',
  'status.checkKey': 'check your key',
  'status.binance': 'Binance market',
  'status.klines': 'Candles',
  'status.depth': 'Depth',
  'status.news': 'News',
  'status.cryptopanic': 'CryptoPanic news',
  'status.fng': 'Sentiment index',
  'status.global': 'Global data',
  'status.blockchain': 'BTC network stats',
  'status.mempool': 'Fees & mempool',
  'status.defillama': 'DefiLlama',
  'status.whale': 'Whale Alert',
  'status.ws': 'WebSocket',
  'sig.type.mean': 'Mean reversion',
  'sig.type.momentum': 'Momentum',
  'sig.type.trend': 'Trend',
  'sig.type.breakout': 'Breakout',
  'sig.type.anomaly': 'Anomaly',
  'sig.type.move': 'Price move',
  'sig.rsiOs.title': '{symbol} RSI oversold {v}',
  'sig.rsiOs.msg': 'RSI is below 30; watch for a mean-reversion bounce, confirmed by trend.',
  'sig.rsiOb.title': '{symbol} RSI overbought {v}',
  'sig.rsiOb.msg': 'RSI is above 70; chasing longs is risky, watch for profit taking.',
  'sig.macdBull.title': '{symbol} MACD golden cross',
  'sig.macdBull.msg': 'MACD histogram turned positive; momentum is shifting bullish.',
  'sig.macdBear.title': '{symbol} MACD death cross',
  'sig.macdBear.msg': 'MACD histogram turned negative; momentum is shifting bearish.',
  'sig.emaBull.title': '{symbol} EMA golden cross',
  'sig.emaBull.msg': 'EMA12 crossed above EMA26; medium-term trend is turning up.',
  'sig.emaBear.title': '{symbol} EMA death cross',
  'sig.emaBear.msg': 'EMA12 crossed below EMA26; medium-term trend is turning down.',
  'sig.bollUp.title': '{symbol} broke above upper band',
  'sig.bollUp.msg': 'Price broke above the upper Bollinger band; watch for trend continuation or reversion.',
  'sig.bollDown.title': '{symbol} broke below lower band',
  'sig.bollDown.msg': 'Price broke below the lower Bollinger band; volatility is rising, manage risk.',
  'sig.anomalyZ.title': '{symbol} anomaly (MAD-Z)',
  'sig.anomalyZ.msg': 'Modified Z-Score {v}; return deviates significantly from the median.',
  'sig.anomalyEwma.title': '{symbol} EWMA move',
  'sig.anomalyEwma.msg': 'EWMA return deviates {v}% from normal volatility; check volume.',
  'sig.move.title': '{symbol} 24h {pct}',
  'sig.move.msg': 'Move exceeds 5% in 24h; watch volume and news.',
  'ai.techSec': 'Technicals',
  'ai.newsSec': 'News',
  'ai.verdictSec': 'Verdict',
  'ai.insightIntro': '{symbol} ({name}) is at {price}{change}. Trend: {trend}; RSI(14) {rsi}; MACD {macd}; price is {bb}.',
  'ai.insightVol': 'ATR is {v}% of price; volatility{vol}.',
  'ai.volHigh': ' is high, watch position sizing',
  'ai.volLow': ' is low, consolidation may precede a move',
  'ai.volMid': ' is neutral',
  'ai.newsSummary': 'In the latest news set, {n} items mention {symbol}: {pos} positive, {neg} negative, {neu} neutral. {tone}',
  'ai.newsTonePos': 'Sentiment is positive and may align with technicals.',
  'ai.newsToneNeg': 'Sentiment is cautious; watch for negative catalysts.',
  'ai.newsToneNeu': 'Mixed signals; trend confirmation depends on flows.',
  'ai.noNews': 'No strongly related news for {symbol} right now; price is mostly flow and macro driven.',
  'ai.headline': 'Latest related item: {title}',
  'ai.fngHigh': 'Market is greedy; be careful chasing.',
  'ai.fngLow': 'Market is fearful; watch for oversold opportunities.',
  'ai.fngMid': 'Sentiment is neutral; trade the signals.',
  'ai.fngSuffix': ' Fear & Greed is {v} ({label}); overall risk appetite is {level}.',
  'ai.verdictBull': 'Trend and sentiment align bullish; consider pullbacks toward moving averages, but avoid late-chasing tops.',
  'ai.verdictBear': 'Weakness is clear and bounces look limited; wait for stabilization or better news.',
  'ai.verdictOversold': 'Short-term oversold; mean reversion is plausible, but avoid heavy left-side sizing before the trend turns.',
  'ai.verdictOverbought': 'Short-term overbought; momentum is strong but chasing is risky. Consider scaling out.',
  'ai.verdictNeutral': 'Buyers and sellers are balanced; wait for an EMA cross or Bollinger breakout.',
  'ai.priceTitle': '{symbol} Live Price',
  'ai.priceHtml': '{symbol} ({name}) is at {price} USDT, 24h {pct}. 24h high {high}, low {low}. Volume ~{vol} {symbol}; quote volume {quote} USDT. Source: {source}',
  'ai.rsiTitle': '{symbol} RSI(14)',
  'ai.rsiHtml': '{symbol} RSI(14) is {v}, in the {state}.',
  'ai.rsiExplain': 'Oversold does not mean an instant bounce; wait for momentum divergence or stabilization.',
  'ai.rsiExplainOb': 'In overbought conditions momentum can persist; chasing increases risk.',
  'ai.rsiExplainNeu': 'In a neutral zone bulls and bears are balanced; use MACD and moving averages.',
  'ai.rsiStateOs': 'oversold zone',
  'ai.rsiStateOb': 'overbought zone',
  'ai.rsiStateNeu': 'neutral zone',
  'ai.trendTitle': '{symbol} Trend Structure',
  'ai.trendHtml': '{symbol} trend: {trend}. EMA12 {e12} / EMA26 {e26}, SMA20 {sma}. {advice}',
  'ai.trendAdviceBull': 'Moving averages are aligned bullish; watch pullbacks to support.',
  'ai.trendAdviceBear': 'Moving averages are bearish; rallies face resistance.',
  'ai.signalTitle': '{symbol} Latest Signals',
  'ai.signalNone': 'No active signals for {symbol}.',
  'ai.newsTitle': '{symbol} Related News',
  'ai.newsNone': 'No strongly related news found for {symbol}.',
  'ai.newsList': 'Latest news mentions {n} related items: {pos} positive / {neg} negative / {neu} neutral.',
  'ai.sentimentTitle': 'Market Sentiment',
  'ai.sentimentHtml': 'Fear & Greed: {v} / 100 ({label}). News set {n}: {pos} positive / {neg} negative / {neu} neutral. {advice}',
  'ai.chainTitle': 'On-chain Data',
  'ai.chainHtml': 'BTC network: {block}. Fees (sat/vB): fastest {f}, half hour {h}, 1 hour {hour}. Top 3 DeFi chains by TVL: {defi}.',
  'ai.chainLoading': 'Data loading',
  'ai.marketTitle': 'Market Overview',
  'ai.marketHtml': 'Crypto market cap ~{mc} USD, 24h volume {vol} USD, BTC dominance {dom}. {fng}',
  'ai.helpTitle': 'Try asking',
  'ai.helpHtml': '{a}, {b}, {c}, {d}, {e}, or ask "what is MACD?".',
  'ai.def.rsi.t': 'RSI (Relative Strength Index)',
  'ai.def.rsi.h': 'RSI measures the relative strength of gains versus losses over a period, from 0 to 100. Above 70 is usually overbought and below 30 oversold; use it with trend context.',
  'ai.def.macd.t': 'MACD (Moving Average Convergence Divergence)',
  'ai.def.macd.h': 'MACD is built from the difference of fast and slow EMAs (DIF), a signal line (DEA) and a histogram. DIF crossing above DEA is a golden cross; below is a death cross.',
  'ai.def.boll.t': 'Bollinger Bands',
  'ai.def.boll.h': 'Bollinger Bands use a middle band (SMA20) and upper/lower bands at ±2 standard deviations. Touching the bands signals wider volatility; breakouts can start trends or revert.',
  'ai.def.ma.t': 'Moving Averages (MA/EMA)',
  'ai.def.ma.h': 'Moving averages smooth price to reveal trend direction. MA is a simple average; EMA weights recent prices more. Crosses are common trend signals.',
  'ai.def.atr.t': 'ATR (Average True Range)',
  'ai.def.atr.h': 'ATR measures average price range; higher values mean more volatility. It is often used to size stops and positions.',
  'ai.def.whale.t': 'Whale',
  'ai.def.whale.h': 'A whale is a wallet or institution holding a large amount of crypto. Large whale transfers and trades are watched as liquidity and sentiment signals.',
  'ai.def.zscore.t': 'Modified Z-Score Anomaly Detection',
  'ai.def.zscore.h': 'The modified Z-Score uses the median and MAD, making it robust to outliers. This app uses it to flag returns that deviate significantly from normal.',
  'brief.marketLine': 'Fear & Greed {fng}, market cap ~{mc} USD{mcchg}. BTC dominance {dom}.',
  'brief.moversTitle': '24h Movers',
  'brief.newsTitle': 'News Sentiment',
  'brief.newsLine': 'News set {n}: {pos} positive / {neg} negative / {neu} neutral; overall tone is {tone}.',
  'brief.headlineTitle': 'Headline',
  'brief.signalsTitle': 'Signals',
  'brief.signalsLine': 'Signal engine found {n} active triggers{high}.',
  'brief.disclaimer': 'Generated locally from public data by a rule engine; not investment advice.',
  'common.close': 'Close',
  'ai.subtitle': 'Natural language market data queries',
  'ai.chatPlaceholder': 'Ask a question, e.g. What is ETH RSI?',
  'ai.reinterpret': 'Reinterpret',
  'chain.table.chain': 'Chain',
  'chain.table.tvl': 'TVL (USD)',
  'chain.table.change': '24h',
  'chain.table.share': 'Share',
  'sig.type.rsi': 'RSI',
  'sig.type.macd': 'MACD',
  'sig.type.ema': 'EMA',
  'sig.type.boll': 'BOLL',
  'status.ticker24': 'REST 24h ticker',
  'status.symbols': '{n} symbols',
  'status.symbols1h': '{n} symbols 1h',
  'status.items': '{n} items',
  'status.txCount': '{n} tx',
  'meta.desc': 'Live prices, candlesticks, indicators, news sentiment and on-chain monitoring',
  'news.cat.all': 'All',
  'news.cat.wallet': 'Wallets',
  'news.cat.policy': 'Policy',
  'news.cat.tech': 'Tech',
  'news.cat.market': 'Market'
};
