window.__LANG_es = {
  'app.name': 'Centro de Inteligencia Cripto',
  'nav.market': 'Mercado',
  'nav.news': 'Noticias',
  'nav.chain': 'On-chain',
  'nav.ai': 'Asistente IA',
  'ask.placeholder': 'Pregunta: técnico de BTC / últimas noticias ETH / sentimiento',
  'ask.submit': 'Preguntar',
  'badge.checking': 'Comprobando fuentes',
  'badge.ws': 'WebSocket en vivo',
  'badge.polling': 'Datos en vivo (polling)',
  'badge.demo': 'Modo datos demo',
  'badge.mixed': 'Algunas fuentes no disponibles',
  'badge.offline': 'Fuentes no disponibles',
  'interval.15m': '15m',
  'interval.1h': '1h',
  'interval.4h': '4h',
  'interval.1d': '1d',
  'overlay.ma': 'MA',
  'overlay.boll': 'BOLL',
  'overlay.vol': 'VOL',
  'chart.loading': 'Cargando velas...',
  'chart.live': 'Datos en vivo de Binance',
  'chart.demo': 'Datos demo (API no disponible)',
  'chart.high': 'Máx',
  'chart.low': 'Mín',
  'chart.vol': 'Vol',
  'chart.open': 'Apertura',
  'chart.close': 'Cierre',
  'chart.source': 'Fuente',
  'indicators.title': 'Indicadores',
  'signals.title': 'Motor de Señales',
  'signals.rescan': 'Reescanear',
  'signals.empty': 'Sin señales activas para {symbol}',
  'signals.high': 'Alta',
  'signals.medium': 'Media',
  'signals.low': 'Normal',
  'metric.rsi': 'RSI(14)',
  'metric.macd': 'MACD',
  'metric.ema': 'EMA12/26',
  'metric.sma': 'SMA20',
  'metric.atr': 'ATR',
  'metric.boll': 'Bollinger',
  'metric.madz': 'MAD-Z',
  'metric.ewma': 'EWMA',
  'hint.rsiNeutral': 'Neutral',
  'hint.rsiOversold': 'Sobreventa',
  'hint.rsiOverbought': 'Sobrecompra',
  'hint.macdBull': 'Impulso alcista',
  'hint.macdBear': 'Impulso bajista',
  'hint.trendBull': 'Alcista',
  'hint.trendBear': 'Bajista',
  'hint.priceAbove': 'Precio por encima',
  'hint.priceBelow': 'Precio por debajo',
  'hint.bollUpper': 'Por encima de banda',
  'hint.bollLower': 'Por debajo de banda',
  'hint.anomalyNormal': 'Normal',
  'hint.anomaly': 'Anomalía',
  'hint.ewmaThreshold': 'Umbral ±{v}%',
  'depth.title': 'Profundidad del Libro',
  'depth.bid': 'Compras',
  'depth.ask': 'Ventas',
  'depth.loading': 'Cargando profundidad...',
  'overview.gauge': 'Índice Miedo y Codicia',
  'overview.totalMc': 'Capitalización',
  'overview.vol24': 'Volumen 24h',
  'overview.btcShare': 'Dominio BTC',
  'overview.ethShare': 'Dominio ETH',
  'overview.movers': 'Movers 24h',
  'overview.change24': '24h',
  'sent.title': 'Radar de Sentimiento IA',
  'sent.scoreLabel': 'Puntuación',
  'sent.tonePos': 'Alcista',
  'sent.toneNeg': 'Cauteloso',
  'sent.toneNeu': 'Neutral',
  'sent.based': 'Análisis local sobre {n} noticias',
  'sent.positive': 'Positivas',
  'sent.neutral': 'Neutras',
  'sent.negative': 'Negativas',
  'sent.local': 'Léxico local',
  'sent.updated': 'actualizado',
  'news.title': 'Flujo de Noticias',
  'news.all': 'Todo',
  'news.allCoins': 'Todas las monedas',
  'news.noMatch': 'No hay noticias que coincidan con los filtros',
  'news.original': 'Original',
  'time.justNow': 'ahora',
  'time.minAgo': 'hace {n} min',
  'time.hourAgo': 'hace {n} h',
  'time.dayAgo': 'hace {n} d',
  'brief.title': 'Informe Diario IA',
  'brief.refresh': 'Actualizar',
  'chain.net': 'Salud de Red BTC',
  'chain.fees': 'Comisiones y Mempool',
  'chain.defi': 'TVL DeFi por Cadena',
  'chain.whale': 'Radar Ballenas',
  'chain.flows': 'Flujos de Exchanges',
  'chain.whaleLive': 'Whale Alert en vivo',
  'chain.whaleDemo': 'Datos demo · API key configurable',
  'chain.flowNote': 'Datos demo · conecta CryptoQuant / Glassnode para producción',
  'chain.block': 'Altura de bloque',
  'chain.tx': 'Transacciones 24h',
  'chain.hashrate': 'Hashrate EH/s',
  'chain.miner': 'Ingresos mineros 24h',
  'chain.fastest': 'Comisión rápida (sat/vB)',
  'chain.half': 'Comisión 30 min',
  'chain.hour': 'Comisión 1 h',
  'chain.mempool': 'Mempool: {n} tx sin confirmar · ~{v} MB',
  'chain.in': 'Entrada al exchange',
  'chain.out': 'Salida del exchange',
  'chain.loading': 'Cargando datos on-chain...',
  'ai.title': 'Preguntas y Respuestas',
  'ai.insight': 'Análisis IA del Mercado',
  'ai.timeline': 'Línea de Señales',
  'ai.none': 'Sin señales registradas',
  'ai.welcomeTitle': 'Bienvenido',
  'ai.welcome': 'Puedes preguntar: {price}, {rsi}, {news}, {sentiment}, {chain}, o "¿qué es MACD?".',
  'ai.preparing': 'Obteniendo velas 1h de {symbol} y calculando indicadores...',
  'ai.suggestions': ['Análisis técnico de BTC', '¿Cuál es el RSI de ETH?', 'Últimas noticias de SOL', '¿Cómo está el sentimiento?', '¿Cómo están los datos on-chain?', '¿Qué son las Bandas de Bollinger?', 'Precio de BTC'],
  'settings.title': 'Fuentes de Datos y API Keys',
  'settings.desc': 'Las claves se guardan solo en este navegador (localStorage) para habilitar fuentes premium. Sin claves se usan APIs públicas y datos demo.',
  'settings.whale': 'Whale Alert API Key (monitoreo real de ballenas)',
  'settings.cryptopanic': 'CryptoPanic API Key (noticias multi-fuente)',
  'settings.cryptocompare': 'CryptoCompare API Key (mayor cuota de noticias)',
  'settings.optional': 'opcional',
  'settings.save': 'Guardar',
  'settings.saved': 'Configuración guardada, recargando fuentes',
  'footer.disclaimer': 'Los datos y noticias provienen de APIs públicas; no son asesoría de inversión',
  'footer.source': 'Fuentes: {live} en vivo / {demo} respaldo · actualizado {time}',
  'toast.switched': 'Cambiado a {symbol}',
  'toast.rescan': 'Motor de señales reescaneado',
  'toast.refreshed': 'Informe actualizado',
  'toast.insightRefreshed': 'Análisis regenerado',
  'status.ok': 'OK',
  'status.unavailable': 'no disponible',
  'status.connecting': 'conectando',
  'status.demo': 'respaldo demo',
  'status.checkKey': 'revisa tu clave',
  'status.binance': 'Mercado Binance',
  'status.klines': 'Velas',
  'status.depth': 'Profundidad',
  'status.news': 'Noticias',
  'status.cryptopanic': 'Noticias CryptoPanic',
  'status.fng': 'Índice de sentimiento',
  'status.global': 'Datos globales',
  'status.blockchain': 'Estadísticas red BTC',
  'status.mempool': 'Comisiones y mempool',
  'status.defillama': 'DefiLlama',
  'status.whale': 'Whale Alert',
  'status.ws': 'WebSocket',
  'sig.type.mean': 'Reversión media',
  'sig.type.momentum': 'Momentum',
  'sig.type.trend': 'Tendencia',
  'sig.type.breakout': 'Ruptura',
  'sig.type.anomaly': 'Anomalía',
  'sig.type.move': 'Movimiento',
  'sig.rsiOs.title': '{symbol} RSI sobreventa {v}',
  'sig.rsiOs.msg': 'RSI por debajo de 30; vigila un rebote de reversión media con la tendencia.',
  'sig.rsiOb.title': '{symbol} RSI sobrecompra {v}',
  'sig.rsiOb.msg': 'RSI por encima de 70; perseguir largos es arriesgado, vigila toma de ganancias.',
  'sig.macdBull.title': '{symbol} cruce dorado MACD',
  'sig.macdBull.msg': 'Histograma MACD positivo; el impulso gira alcista.',
  'sig.macdBear.title': '{symbol} cruce de muerte MACD',
  'sig.macdBear.msg': 'Histograma MACD negativo; el impulso gira bajista.',
  'sig.emaBull.title': '{symbol} cruce dorado EMA',
  'sig.emaBull.msg': 'EMA12 cruzó por encima de EMA26; tendencia media alcista.',
  'sig.emaBear.title': '{symbol} cruce de muerte EMA',
  'sig.emaBear.msg': 'EMA12 cruzó por debajo de EMA26; tendencia media bajista.',
  'sig.bollUp.title': '{symbol} rompió banda superior',
  'sig.bollUp.msg': 'Precio rompió la banda superior de Bollinger; vigila continuación o reversión.',
  'sig.bollDown.title': '{symbol} rompió banda inferior',
  'sig.bollDown.msg': 'Precio rompió la banda inferior; la volatilidad sube, gestiona el riesgo.',
  'sig.anomalyZ.title': '{symbol} anomalía (MAD-Z)',
  'sig.anomalyZ.msg': 'Z-Score modificado {v}; retorno muy alejado de la mediana.',
  'sig.anomalyEwma.title': '{symbol} movimiento EWMA',
  'sig.anomalyEwma.msg': 'Retorno EWMA se desvía {v}% de la volatilidad normal; revisa volumen.',
  'sig.move.title': '{symbol} 24h {pct}',
  'sig.move.msg': 'Movimiento superior a 5% en 24h; vigila volumen y noticias.',
  'ai.techSec': 'Técnico',
  'ai.newsSec': 'Noticias',
  'ai.verdictSec': 'Conclusión',
  'ai.insightIntro': '{symbol} ({name}) cotiza en {price}{change}. Tendencia: {trend}; RSI(14) {rsi}; MACD {macd}; precio {bb}.',
  'ai.insightVol': 'ATR es {v}% del precio; volatilidad{vol}.',
  'ai.volHigh': ' alta, controla el tamaño de la posición',
  'ai.volLow': ' baja, consolidación antes de un movimiento',
  'ai.volMid': ' neutral',
  'ai.newsSummary': 'En las últimas noticias, {n} mencionan {symbol}: {pos} positivas, {neg} negativas, {neu} neutras. {tone}',
  'ai.newsTonePos': 'El sentimiento es positivo y puede alinearse con el análisis técnico.',
  'ai.newsToneNeg': 'El sentimiento es cauto; vigila catalizadores negativos.',
  'ai.newsToneNeu': 'Señales mixtas; la confirmación depende de los flujos.',
  'ai.noNews': 'Sin noticias muy relacionadas con {symbol}; el precio depende de flujos y macro.',
  'ai.headline': 'Última relacionada: {title}',
  'ai.fngHigh': 'El mercado está codicioso; ten cuidado al perseguir.',
  'ai.fngLow': 'El mercado tiene miedo; busca oportunidades de sobreventa.',
  'ai.fngMid': 'Sentimiento neutral; opera las señales.',
  'ai.fngSuffix': ' Miedo y Codicia {v} ({label}); apetito de riesgo {level}.',
  'ai.verdictBull': 'Tendencia y sentimiento alcistas; considera retrocesos a medias móviles sin perseguir máximos.',
  'ai.verdictBear': 'Debilidad clara y rebotes limitados; espera estabilización o mejores noticias.',
  'ai.verdictOversold': 'Sobreventa a corto plazo; posible reversión media, evita posiciones pesadas antes de que gire la tendencia.',
  'ai.verdictOverbought': 'Sobrecompra a corto plazo; el impulso es fuerte pero perseguir es arriesgado. Considera recoger beneficios.',
  'ai.verdictNeutral': 'Compradores y vendedores equilibrados; espera cruce EMA o ruptura de Bollinger.',
  'ai.priceTitle': '{symbol} Precio en Vivo',
  'ai.priceHtml': '{symbol} ({name}) cotiza en {price} USDT, 24h {pct}. Máximo 24h {high}, mínimo {low}. Volumen ~{vol} {symbol}; volumen de cotización {quote} USDT. Fuente: {source}',
  'ai.rsiTitle': '{symbol} RSI(14)',
  'ai.rsiHtml': 'RSI(14) de {symbol} es {v}, en {state}.',
  'ai.rsiExplain': 'Sobreventa no implica rebote inmediato; espera divergencia o estabilización.',
  'ai.rsiExplainOb': 'En sobrecompra el impulso puede continuar; perseguir aumenta el riesgo.',
  'ai.rsiExplainNeu': 'En zona neutral hay equilibrio; usa MACD y medias móviles.',
  'ai.rsiStateOs': 'zona de sobreventa',
  'ai.rsiStateOb': 'zona de sobrecompra',
  'ai.rsiStateNeu': 'zona neutral',
  'ai.trendTitle': '{symbol} Estructura de Tendencia',
  'ai.trendHtml': 'Tendencia de {symbol}: {trend}. EMA12 {e12} / EMA26 {e26}, SMA20 {sma}. {advice}',
  'ai.trendAdviceBull': 'Medias móviles alineadas alcistas; vigila retrocesos al soporte.',
  'ai.trendAdviceBear': 'Medias móviles bajistas; los rebotes encuentran resistencia.',
  'ai.signalTitle': '{symbol} Últimas Señales',
  'ai.signalNone': 'Sin señales activas para {symbol}.',
  'ai.newsTitle': '{symbol} Noticias Relacionadas',
  'ai.newsNone': 'No se encontraron noticias muy relacionadas con {symbol}.',
  'ai.newsList': 'Últimas noticias: {n} relacionadas, {pos} positivas / {neg} negativas / {neu} neutras.',
  'ai.sentimentTitle': 'Sentimiento del Mercado',
  'ai.sentimentHtml': 'Miedo y Codicia: {v} / 100 ({label}). Noticias {n}: {pos} positivas / {neg} negativas / {neu} neutras. {advice}',
  'ai.chainTitle': 'Datos On-chain',
  'ai.chainHtml': 'Red BTC: {block}. Comisiones (sat/vB): rápida {f}, 30 min {h}, 1 hora {hour}. Top 3 TVL DeFi: {defi}.',
  'ai.chainLoading': 'Cargando datos',
  'ai.marketTitle': 'Visión General',
  'ai.marketHtml': 'Capitalización cripto ~{mc} USD, volumen 24h {vol} USD, dominio BTC {dom}. {fng}',
  'ai.helpTitle': 'Prueba preguntando',
  'ai.helpHtml': '{a}, {b}, {c}, {d}, {e}, o pregunta "¿qué es MACD?".',
  'ai.def.rsi.t': 'RSI (Índice de Fuerza Relativa)',
  'ai.def.rsi.h': 'El RSI mide la fuerza relativa de ganancias frente a pérdidas, de 0 a 100. Sobre 70 suele ser sobrecompra y bajo 30 sobreventa; úsalo con contexto de tendencia.',
  'ai.def.macd.t': 'MACD (Convergencia/Divergencia de Medias)',
  'ai.def.macd.h': 'El MACD se forma con la diferencia de EMAs rápidas y lentas (DIF), una línea de señal (DEA) y un histograma. DIF cruzando sobre DEA es un cruce dorado; bajo, cruce de muerte.',
  'ai.def.boll.t': 'Bandas de Bollinger',
  'ai.def.boll.h': 'Las Bandas de Bollinger usan una banda media (SMA20) y bandas superior/inferior a ±2 desviaciones estándar. Tocar las bandas indica más volatilidad; la ruptura puede iniciar tendencia o revertir.',
  'ai.def.ma.t': 'Medias Móviles (MA/EMA)',
  'ai.def.ma.h': 'Las medias móviles suavizan el precio para revelar tendencia. MA es promedio simple; EMA pondera más los precios recientes. Los cruces son señales comunes.',
  'ai.def.atr.t': 'ATR (Rango Verdadero Medio)',
  'ai.def.atr.h': 'El ATR mide el rango medio del precio; valores altos implican más volatilidad. Se usa para dimensionar stops y posiciones.',
  'ai.def.whale.t': 'Ballena (Whale)',
  'ai.def.whale.h': 'Una ballena es un monedero o institución con grandes tenencias cripto. Sus transferencias y operaciones se vigilan como señales de liquidez y sentimiento.',
  'ai.def.zscore.t': 'Detección de Anomalías con Z-Score Modificado',
  'ai.def.zscore.h': 'El Z-Score modificado usa mediana y MAD, robusto ante valores atípicos. Esta app lo usa para marcar retornos que se desvían de lo normal.',
  'brief.marketLine': 'Miedo y Codicia {fng}, capitalización ~{mc} USD{mcchg}. Dominio BTC {dom}.',
  'brief.moversTitle': 'Movers 24h',
  'brief.newsTitle': 'Sentimiento de Noticias',
  'brief.newsLine': 'Noticias {n}: {pos} positivas / {neg} negativas / {neu} neutras; tono {tone}.',
  'brief.headlineTitle': 'Titular',
  'brief.signalsTitle': 'Señales',
  'brief.signalsLine': 'El motor detecta {n} señales activas{high}.',
  'brief.disclaimer': 'Generado localmente con datos públicos por un motor de reglas; no es asesoría de inversión.'
};
